# Uncomment the next line to define a global platform for your project
platform :ios, '17.4'

target 'blinkoo components example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for blinkoo components example
  # TODO add real depedency when uploaded
  pod 'blinkoo-ios-components', :path => '/Users/davide.quadrelli/IdeaProjects/blinkoo-app-sdk/ios'

end
